esnode:
  build: docker/elasticsearch/
  environment:
    - NETWORK_PUBLISH_HOST
esgateway:
  build: docker/elasticsearch/
  environment:
    - NETWORK_PUBLISH_HOST
  ports:
    - '9200:9200'
    - '9300:9300'
kibana4:
  build: docker/kibana4/
  ports:
    - '5601:5601'
  links:
    - esgateway
