esNode:
  image: kumina/elasticsearch
  environment:
    - NETWORK_PUBLISH_HOST
esGateway:
  image: kumina/elasticsearch
  environment:
    - NETWORK_PUBLISH_HOST
  ports:
    - '9200:9200'
    - '9300:9300'
kibana:
  image: kumina/kibana4
  ports:
    - '5601:5601'
  links:
    - esGateway
